POST https://afafg-pq-apfx01.afcorp.afg/Afc.S125.Services.ApplicationService.Implementation/OnePageSummaryService.svc/basic HTTP/1.1
Accept-Encoding: gzip,deflate
Content-Type: text/xml;charset=UTF-8
SOAPAction: "http://tempuri.org/IOnePageSummaryService/GetOnePageSummaryData"
Content-Length: 328
Host: afafg-pq-apfx01.afcorp.afg
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.1.1 (java 1.5)
Authorization: Basic YXBmeDAxcWE6dXNlcm5hbWU6IEFGR1xhcGZ4MDFxYSAgcGFzc3dvcmQ6IFBkMVlkU3VqWlg=

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/">
   <soapenv:Header/>
   <soapenv:Body>
      <tem:GetOnePageSummaryData>
         <!--Optional:-->
         <tem:planId>7365</tem:planId>
      </tem:GetOnePageSummaryData>
   </soapenv:Body>
</soapenv:Envelope>
